version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - movie-system
    env_file:
      - .env
    ports:
      - "5001:5001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 100s
      timeout: 5s
      retries: 3
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   networks:
  #     - movie-system
  #   depends_on:
  #     - backend

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - movie-system
networks:
  movie-system:
    driver: bridge
